### ISSUE TITLE
Checklist Planejamento

### ISSUE THREAD

**Issue by joaovtk** [joaovtk/world-store#2]
- [ ] Diagrama de **Classe**
- [ ] Diagrama de **Sequencia**
     - [ ]  - **Usuario**
     - [ ] - **Comerciante**
- [ ] Diagrama de **Caso de Uso**
